

declare abstract class Window_Selectable extends Window_Scrollable{
  protected _index: number;
  protected _cursorFixed: boolean;
  protected _cursorAll: boolean;
  protected _helpWindow: Window_Help;
  protected _handlers: Record<string, Function>;
  protected _doubleTouch: boolean;
  protected _canRepeat: boolean;

  constructor(rect: Rectangle);
  override initialize(rect: Rectangle);
  index(): number;
  cursorFixed(): boolean;
  setCursorFixed(cursorFixed: boolean);
  cursorAll(): boolean;
  setCursorAll(cursorAll: boolean);
  maxCols(): number;
  maxItems(): number;
  colSpacing(): number;
  rowSpacing(): number;
  override itemWidth(): number;
  override itemHeight(): number;
  contentsHeight(): number;
  maxRows(): number;
  overallHeight(): number;
  override activate();
  override deactivate();
  select(index: number);
  forceSelect(index: number);
  smoothSelect(index: number);
  deselect();
  reselect();
  row(): number;
  topRow(): number;
  maxTopRow(): number;
  setTopRow(row: number);
  maxPageRows(): number;
  maxPageItems(): number;
  maxVisibleItems(): number;
  isHorizontal(): boolean;
  topIndex(): number;
  itemRect(index: number): Rectangle;
  itemRectWithPadding(index: number): Rectangle;
  ItemLineRect(index: number): Rectangle;
  setHelpWindow(helpWindow: Window_Help);
  showHelpWindow();
  hideHelpWindow();
  setHandler(symbol: string,method: Function);
  isHandled(symbol: string): boolean;
  callHandler(symbol: string);
  isOpenAndActive(): boolean;
  isCursorMovable(): boolean;
  cursorDown(wrap: boolean);
  cursorUp(wrap:boolean);
  cursorRight(wrap: boolean);
  cursorLeft(wrap: boolean);
  cursorPagedown();
  cursorPageup();
  isScrollEnabled(): boolean;
  update();
  proccessCursorMove();
  proccessTouch();
  isHoverEnabled(): boolean;
  onTouchSelect(trigger: boolean);
  onTouchOk();
  onTouchCancel();
  hitIndex(): number;
  hitTest(x: number,y: number): number;
  isTouchOkEnabled(): boolean;
  isOkEnabled(): boolean;
  isCancelEnabled(): boolean;
  isOkTriggered(): boolean;
  isCancelTriggered(): boolean;
  processOk();
  callOkHandler();
  processCancel();
  callCancelHandler();
  processPageup();
  proccessPagedown();
  updateInputData();
  ensureCursorVisible(smooth: boolean);
  callUpdateHelp();
  updateHelp();
  // TODO : what is the type for this?
  setHelpWindowItem(item);
  isCurrentItemEnabled(): boolean;
  drawAllItems();
  abstract drawItem(index: number);
  clearItem(index: number);
  drawItemBackground(index: number);
  drawBackgroundRect(rect: Rectangle);
  redrawItem(index: number);
  redrawCurrentItem();
  refresh();
  override paint();
  refreshCursor();
  refreshCursorForAll();
}