

declare class Scene_Battle extends Scene_Message {

  protected _actorCommandWindow: Window_ActorCommand;
  protected _actorWindow: Window_BattleActor;
  protected _cancelButton: Sprite_Button;
  protected _enemyWindow: Window_BattleEnemy;
  protected _helpWindow: Window_Help;
  protected _itemWindow: Window_BattleItem;
  protected _logWindow: Window_BattleLog;
  protected _partyCommandWindow: Window_PartyCommand;
  protected _skillWindow: Window_BattleSkill;
  protected _spriteset: Spriteset_Battle;
  protected _statusWindow: Window_BattleStatus;

  constructor();
  override initialize(): void;
  override create(): void;
  override start(): void;
  override update(): void;
  updateVisibility(): void;
  updateBattleProcess(): void;
  isTimeActive(): boolean;
  isAnyInputWindowActive(): boolean;
  changeInputWindow(): void;
  override stop(): void;
  override terminate(): void;
  shouldAutosave(): boolean;
  needsSlowFadeOut(): boolean;
  updateLogWindowVisibility(): void;
  updateStatusWindowVisibility(): void;
  shouldOpenStatusWindow(): boolean;
  updateStatusWindowPosition(): void;
  statusWindowX(): number;
  updateInputWindowVisibility(): void;
  needsInputWindowChange(): boolean;
  updateCancelButton(): void;
  createDisplayObjects(): void;
  createSpriteset(): void;
  createAllWindows(): void;
  createLogWindow(): void;
  logWindowRect(): Rectangle;
  createStatusWindow(): void;
  statusWindowRect(): Rectangle;
  createPartyCommandWindow(): void;
  partyCommandWindowRect(): Rectangle;
  createActorCommandWindow(): void;
  actorCommandWindowRect(): Rectangle;
  createHelpWindow(): void;
  helpWindowRect():Rectangle;
  createSkillWindow(): void;
  skillWindowRect(): Rectangle;
  createItemWindow(): void;
  itemWindowRect(): Rectangle;
  createActorWindow(): void;
  actorWindowRect(): Rectangle;
  createEnemyWindow(): void;
  enemyWindowRect(): Rectangle;
  helpAreaTop(): number;
  helpAreaBottom(): number;
  helpAreaHeight(): number;
  override buttonAreaTop(): number;
  windowAreaHeight(): number;
  createButtons(): void;
  createCancelButton(): void;
  closeCommandWindows(): void;
  hideSubInputWindows(): void;
  startPartyCommandSelection(): void;
  commandFight(): void;
  commandEscape(): void;
  startActorCommandSelection(): void;
  commandAttack(): void;
  commandSkill(): void;
  commandGuard(): void;
  commandItem(): void;
  commandCancel(): void;
  selectNextCommand(): void;
  selectPreviousCommand(): void;
  startActorSelection(): void;
  onActorOk(): void;
  onActorCancel(): void;
  startEnemySelection(): void;
  onEnemyOk(): void;
  onSkillOk(): void;
  onSkillCancel(): void;
  onItemOk(): void;
  onItemCancel(): void;
  onSelectAction(): void;
  endCommandSelection(): void;
}